import { useEffect, useState } from 'react';
import { MapPin, Plus, Trash2 } from 'lucide-react';
import { adminApi } from '../../api/admin';
import { useAuth } from '../../context/AuthContext';
import type { AdminDestinoRow } from '../../types/admin';
import type { Place } from '../../types';

const EMPTY = { nombre: '', categoria: 'Patrimonio', descripcion: '', latitud: 40, longitud: -3.5, website: '', sortOrder: 0 };
export default function AdminPlaces({ destinos }: { destinos: AdminDestinoRow[] }) {
  const { token } = useAuth(); const [destinoId, setDestinoId] = useState(''); const [places, setPlaces] = useState<Place[]>([]); const [form, setForm] = useState(EMPTY); const [error, setError] = useState('');
  useEffect(() => { if (!destinoId || !token) { setPlaces([]); return; } adminApi.listPlaces(destinoId, token).then(setPlaces).catch(() => setError('No se pudieron cargar los lugares')); }, [destinoId, token]);
  const create = async (event: React.FormEvent) => { event.preventDefault(); if (!token || !destinoId) return; setError(''); try { const place = await adminApi.createPlace(destinoId, { ...form, isActive: true } as Omit<Place, 'id'>, token); setPlaces((rows) => [...rows, place]); setForm(EMPTY); } catch (err) { setError(err instanceof Error ? err.message : 'No se pudo crear'); } };
  const remove = async (id: string) => { if (!token) return; await adminApi.deletePlace(id, token); setPlaces((rows) => rows.filter((place) => place.id !== id)); };
  return <section className="admin-reviews admin-places"><h2>Lugares cercanos</h2><p>Selecciona un destino y añade puntos que aparecerán en su ficha.</p><select className="ui-input" value={destinoId} onChange={(event) => setDestinoId(event.target.value)}><option value="">Selecciona destino</option>{destinos.map((destino) => <option key={destino.id} value={destino.id}>{destino.nombre}</option>)}</select>{destinoId && <form className="admin-places__form" onSubmit={create}><input className="ui-input" placeholder="Nombre" value={form.nombre} onChange={(e) => setForm({ ...form, nombre: e.target.value })} required /><input className="ui-input" placeholder="Categoría" value={form.categoria} onChange={(e) => setForm({ ...form, categoria: e.target.value })} required /><input className="ui-input" type="number" step="any" placeholder="Latitud" value={form.latitud} onChange={(e) => setForm({ ...form, latitud: Number(e.target.value) })} required /><input className="ui-input" type="number" step="any" placeholder="Longitud" value={form.longitud} onChange={(e) => setForm({ ...form, longitud: Number(e.target.value) })} required /><textarea className="ui-input" placeholder="Descripción" value={form.descripcion} onChange={(e) => setForm({ ...form, descripcion: e.target.value })} /><input className="ui-input" placeholder="Web opcional" value={form.website} onChange={(e) => setForm({ ...form, website: e.target.value })} /><button className="btn-cta" type="submit"><Plus className="icon-sm" /> Añadir lugar</button></form>}{error && <p className="collection-collab__error">{error}</p>}<div className="admin-reviews">{places.map((place) => <article key={place.id} className="admin-reviews__item"><div><MapPin className="icon-sm" /><strong>{place.nombre}</strong> · {place.categoria}<p>{place.descripcion}</p></div><button type="button" className="btn-pill" onClick={() => remove(place.id)}><Trash2 className="icon-sm" /> Eliminar</button></article>)}</div></section>;
}
