import { useEffect, useMemo, useState } from 'react';
import { Building2, Edit3, MapPin, MessageSquare, Plus, Search, ShieldCheck, Trash2, X } from 'lucide-react';
import { api, plain } from '../lib/api';
import { useAuth } from '../lib/state';
import type { Destino, Municipio, Place, Review } from '../types';
import { Button, Empty, Field, Loader, Notice, PageHeading, Shell } from '../components/ui';

type Tab = 'destinos' | 'municipios' | 'reviews' | 'places';
const emptyDestination: Partial<Destino> = { nombre: '', ubicacion: '', presupuesto: 'Medio', masificacion: 'Medio', tipoTurismoPrincipal: '', tipoTurismoSecundario: '', descripcion: '', imprescindibles: '', imagen: '', mesesJulioAgosto: 70, mesesMayJunSeptOct: 40, mesesNovAbril: 20 };

export default function AdminPage() {
  const { user, token, loading: authLoading } = useAuth(); const [tab, setTab] = useState<Tab>('destinos'); const [destinos, setDestinos] = useState<Destino[]>([]); const [municipios, setMunicipios] = useState<Municipio[]>([]); const [reviews, setReviews] = useState<Review[]>([]); const [places, setPlaces] = useState<Place[]>([]); const [selectedDestination, setSelectedDestination] = useState(''); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [destinationForm, setDestinationForm] = useState<Partial<Destino> | null>(null); const [municipioForm, setMunicipioForm] = useState<Partial<Municipio> | null>(null); const [placeForm, setPlaceForm] = useState<Partial<Place> | null>(null);
  const load = async () => { if (!token || user?.role !== 'admin') return; setLoading(true); setError(''); try { const [d, m, r] = await Promise.all([api<Destino[]>('/admin/destinos', {}, token), api<Municipio[]>('/admin/municipios', {}, token), api<Review[]>('/admin/reviews', {}, token)]); setDestinos(d); setMunicipios(m); setReviews(r); if (!selectedDestination && d[0]) setSelectedDestination(d[0].id); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se pudo cargar la administración'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [token, user?.role]);
  useEffect(() => { if (token && selectedDestination) api<Place[]>(`/admin/destinos/${selectedDestination}/places`, {}, token).then(setPlaces); }, [token, selectedDestination]);
  const filteredDestinations = useMemo(() => destinos.filter((item) => item.nombre.toLowerCase().includes(query.toLowerCase())), [destinos, query]);
  const saveDestination = async (event: React.FormEvent) => { event.preventDefault(); if (!token || !destinationForm) return; const payload = { ...destinationForm, mesesJulioAgosto: Number(destinationForm.mesesJulioAgosto), mesesMayJunSeptOct: Number(destinationForm.mesesMayJunSeptOct), mesesNovAbril: Number(destinationForm.mesesNovAbril) }; await api(`/admin/destinos${destinationForm.id ? `/${destinationForm.id}` : ''}`, { method: destinationForm.id ? 'PUT' : 'POST', body: JSON.stringify(payload) }, token); setDestinationForm(null); await load(); };
  const saveMunicipio = async (event: React.FormEvent) => { event.preventDefault(); if (!token || !municipioForm) return; await api(`/admin/municipios${municipioForm.id ? `/${municipioForm.id}` : ''}`, { method: municipioForm.id ? 'PUT' : 'POST', body: JSON.stringify(municipioForm) }, token); setMunicipioForm(null); await load(); };
  const savePlace = async (event: React.FormEvent) => { event.preventDefault(); if (!token || !placeForm || !selectedDestination) return; const path = placeForm.id ? `/admin/places/${placeForm.id}` : `/admin/destinos/${selectedDestination}/places`; await api(path, { method: placeForm.id ? 'PUT' : 'POST', body: JSON.stringify({ ...placeForm, latitud: Number(placeForm.latitud), longitud: Number(placeForm.longitud) }) }, token); setPlaceForm(null); setPlaces(await api<Place[]>(`/admin/destinos/${selectedDestination}/places`, {}, token)); };
  const remove = async (kind: 'destinos' | 'municipios' | 'places', id: string) => { if (!token || !confirm('¿Eliminar este elemento definitivamente?')) return; await api(`/admin/${kind}/${id}`, { method: 'DELETE' }, token); if (kind === 'places') setPlaces((items) => items.filter((item) => item.id !== id)); else await load(); };
  const moderate = async (id: string, status: 'published' | 'hidden') => { if (!token) return; await api(`/admin/reviews/${id}`, { method: 'PATCH', body: JSON.stringify({ status }) }, token); await load(); };
  if (authLoading) return <Shell><Loader /></Shell>;
  if (!user || user.role !== 'admin') return <Shell footer={false}><section className="status-page"><Empty headingLevel="h1" icon={<ShieldCheck />} title="Acceso restringido">Esta zona solo está disponible para administradores.</Empty></section></Shell>;
  return <Shell footer={false}><PageHeading kicker="Back office" title="Administración"><p>Edita la información que alimenta TravSeeker. Los cambios afectan al sitio público.</p></PageHeading><div className="admin-layout"><nav className="admin-nav" aria-label="Administración">{([['destinos','Destinos',MapPin],['municipios','Municipios',Building2],['reviews','Reseñas',MessageSquare],['places','Lugares',MapPin]] as const).map(([id,label,Icon]) => <button key={id} className={tab === id ? 'is-active' : ''} onClick={() => setTab(id)}><Icon /> {label}<span>{id === 'destinos' ? destinos.length : id === 'municipios' ? municipios.length : id === 'reviews' ? reviews.length : places.length}</span></button>)}</nav><section className="admin-workspace">{error && <Notice tone="error">{error}</Notice>}{loading ? <Loader /> : <>
    {tab === 'destinos' && <><header className="admin-workspace__head"><div className="admin-search"><Search /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar destino" /></div><Button onClick={() => setDestinationForm({ ...emptyDestination })}><Plus /> Nuevo destino</Button></header><div className="admin-list">{filteredDestinations.map((item) => <article key={item.id}><div><span>{plain(item.ubicacion)}</span><h2>{item.nombre}</h2><p>{plain(item.tipoTurismoPrincipal)} · {plain(item.presupuesto)}</p></div><div><button onClick={() => setDestinationForm(item)} aria-label={`Editar ${item.nombre}`}><Edit3 /></button><button onClick={() => void remove('destinos', item.id)} aria-label={`Eliminar ${item.nombre}`}><Trash2 /></button></div></article>)}</div></>}
    {tab === 'municipios' && <><header className="admin-workspace__head"><div><h2>Municipios</h2><p>Catálogo reutilizable en los destinos.</p></div><Button onClick={() => setMunicipioForm({ nombre: '', precios: '', conexiones: '', tipoTurismo: '' })}><Plus /> Nuevo municipio</Button></header><div className="admin-list">{municipios.map((item) => <article key={item.id}><div><h2>{item.nombre}</h2><p>{plain(item.precios)} · {plain(item.conexiones)}</p></div><div><button onClick={() => setMunicipioForm(item)} aria-label={`Editar ${item.nombre}`}><Edit3 /></button><button onClick={() => void remove('municipios', item.id)} aria-label={`Eliminar ${item.nombre}`}><Trash2 /></button></div></article>)}</div></>}
    {tab === 'reviews' && <><header className="admin-workspace__head"><div><h2>Moderación</h2><p>Publica u oculta aportaciones de la comunidad.</p></div></header><div className="admin-list">{reviews.map((review) => <article key={review.id}><div><span>{review.destino?.nombre || 'Destino'}</span><h2>{review.rating}/5 · {review.user?.nombre || 'Usuario'}</h2><p>{review.comment || 'Sin comentario'}</p></div><div><Button variant={review.status === 'published' ? 'secondary' : 'primary'} onClick={() => void moderate(review.id, review.status === 'published' ? 'hidden' : 'published')}>{review.status === 'published' ? 'Ocultar' : 'Publicar'}</Button></div></article>)}</div></>}
    {tab === 'places' && <><header className="admin-workspace__head"><select value={selectedDestination} onChange={(e) => setSelectedDestination(e.target.value)} aria-label="Destino para gestionar lugares">{destinos.map((item) => <option key={item.id} value={item.id}>{item.nombre}</option>)}</select><Button onClick={() => setPlaceForm({ nombre: '', categoria: '', descripcion: '', latitud: 40, longitud: -3, website: '' })}><Plus /> Nuevo lugar</Button></header><div className="admin-list">{places.map((place) => <article key={place.id}><div><span>{place.categoria}</span><h2>{place.nombre}</h2><p>{place.descripcion || 'Sin descripción'}</p></div><div><button onClick={() => setPlaceForm(place)}><Edit3 /></button><button onClick={() => void remove('places', place.id)}><Trash2 /></button></div></article>)}</div></>}
  </>}</section></div>
  {destinationForm && <AdminModal title={destinationForm.id ? 'Editar destino' : 'Nuevo destino'} onClose={() => setDestinationForm(null)}><form onSubmit={saveDestination}><div className="form-grid"><Field label="Nombre" htmlFor="admin-name"><input id="admin-name" value={destinationForm.nombre || ''} onChange={(e) => setDestinationForm({ ...destinationForm, nombre: e.target.value })} required /></Field><Field label="Ubicación" htmlFor="admin-location"><input id="admin-location" value={destinationForm.ubicacion || ''} onChange={(e) => setDestinationForm({ ...destinationForm, ubicacion: e.target.value })} required /></Field><Field label="Presupuesto" htmlFor="admin-budget"><input id="admin-budget" value={destinationForm.presupuesto || ''} onChange={(e) => setDestinationForm({ ...destinationForm, presupuesto: e.target.value })} required /></Field><Field label="Afluencia" htmlFor="admin-crowd"><input id="admin-crowd" value={destinationForm.masificacion || ''} onChange={(e) => setDestinationForm({ ...destinationForm, masificacion: e.target.value })} required /></Field><Field label="Turismo principal" htmlFor="admin-type"><input id="admin-type" value={destinationForm.tipoTurismoPrincipal || ''} onChange={(e) => setDestinationForm({ ...destinationForm, tipoTurismoPrincipal: e.target.value })} required /></Field><Field label="Imagen" htmlFor="admin-image"><input id="admin-image" value={destinationForm.imagen || ''} onChange={(e) => setDestinationForm({ ...destinationForm, imagen: e.target.value })} required /></Field></div><Field label="Descripción" htmlFor="admin-description"><textarea id="admin-description" value={destinationForm.descripcion || ''} onChange={(e) => setDestinationForm({ ...destinationForm, descripcion: e.target.value })} required /></Field><Field label="Imprescindibles" htmlFor="admin-essentials"><textarea id="admin-essentials" value={destinationForm.imprescindibles || ''} onChange={(e) => setDestinationForm({ ...destinationForm, imprescindibles: e.target.value })} /></Field><div className="form-grid form-grid--3">{([['mesesNovAbril','Nov–abr'],['mesesMayJunSeptOct','Entretiempo'],['mesesJulioAgosto','Jul–ago']] as const).map(([key,label]) => <Field key={key} label={label} htmlFor={key}><input id={key} type="number" min="0" max="100" value={destinationForm[key] || 0} onChange={(e) => setDestinationForm({ ...destinationForm, [key]: Number(e.target.value) })} /></Field>)}</div><Button type="submit">Guardar destino</Button></form></AdminModal>}
  {municipioForm && <AdminModal title={municipioForm.id ? 'Editar municipio' : 'Nuevo municipio'} onClose={() => setMunicipioForm(null)}><form onSubmit={saveMunicipio}><Field label="Nombre" htmlFor="mun-name"><input id="mun-name" value={municipioForm.nombre || ''} onChange={(e) => setMunicipioForm({ ...municipioForm, nombre: e.target.value })} required /></Field><Field label="Precios" htmlFor="mun-price"><input id="mun-price" value={municipioForm.precios || ''} onChange={(e) => setMunicipioForm({ ...municipioForm, precios: e.target.value })} required /></Field><Field label="Conexiones" htmlFor="mun-conn"><textarea id="mun-conn" value={municipioForm.conexiones || ''} onChange={(e) => setMunicipioForm({ ...municipioForm, conexiones: e.target.value })} required /></Field><Field label="Tipo de turismo" htmlFor="mun-type"><input id="mun-type" value={municipioForm.tipoTurismo || ''} onChange={(e) => setMunicipioForm({ ...municipioForm, tipoTurismo: e.target.value })} /></Field><Button type="submit">Guardar municipio</Button></form></AdminModal>}
  {placeForm && <AdminModal title={placeForm.id ? 'Editar lugar' : 'Nuevo lugar'} onClose={() => setPlaceForm(null)}><form onSubmit={savePlace}><Field label="Nombre" htmlFor="place-name"><input id="place-name" value={placeForm.nombre || ''} onChange={(e) => setPlaceForm({ ...placeForm, nombre: e.target.value })} required /></Field><Field label="Categoría" htmlFor="place-category"><input id="place-category" value={placeForm.categoria || ''} onChange={(e) => setPlaceForm({ ...placeForm, categoria: e.target.value })} required /></Field><Field label="Descripción" htmlFor="place-description"><textarea id="place-description" value={placeForm.descripcion || ''} onChange={(e) => setPlaceForm({ ...placeForm, descripcion: e.target.value })} /></Field><div className="form-grid"><Field label="Latitud" htmlFor="place-lat"><input id="place-lat" type="number" step="any" value={placeForm.latitud || 0} onChange={(e) => setPlaceForm({ ...placeForm, latitud: Number(e.target.value) })} required /></Field><Field label="Longitud" htmlFor="place-lng"><input id="place-lng" type="number" step="any" value={placeForm.longitud || 0} onChange={(e) => setPlaceForm({ ...placeForm, longitud: Number(e.target.value) })} required /></Field></div><Button type="submit">Guardar lugar</Button></form></AdminModal>}
  </Shell>;
}

function AdminModal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="modal-backdrop"><section className="modal modal--wide" role="dialog" aria-modal="true" aria-labelledby="admin-modal-title"><button className="modal__close" onClick={onClose} aria-label="Cerrar"><X /></button><h2 id="admin-modal-title">{title}</h2>{children}</section></div>; }
