import { useEffect, useMemo, useState } from 'react';
import { Building2, Edit3, ExternalLink, MapPin, MessageSquare, Plus, Search, ShieldCheck, Trash2 } from 'lucide-react';
import { api, plain } from '../lib/api';
import { useAuth } from '../lib/state';
import { TourismMark } from '../lib/tourism';
import type { Destino, Municipio, Place, Review } from '../types';
import { Button, Empty, Field, Loader, Notice, PageHeading, Shell } from '../components/ui';
import { AdminModal } from '../components/admin/AdminModal';
import { CoordinatePicker } from '../components/admin/CoordinatePicker';
import { DestinationEditor } from '../components/admin/DestinationEditor';

type Tab = 'destinos' | 'municipios' | 'reviews' | 'places';
const emptyDestination: Partial<Destino> = { nombre: '', ubicacion: '', presupuesto: 'Medio', masificacion: 'Medio', tipoTurismoPrincipal: 'Cultural', tipoTurismoSecundario: 'Patrimonial', descripcion: '', imprescindibles: '', imagen: '', destinosItem: '', latitud: null, longitud: null, municipios: [], mesesJulioAgosto: 70, mesesMayJunSeptOct: 45, mesesNovAbril: 25 };

export default function AdminPage() {
  const { user, token, loading: authLoading } = useAuth();
  const [tab, setTab] = useState<Tab>('destinos');
  const [destinos, setDestinos] = useState<Destino[]>([]); const [municipios, setMunicipios] = useState<Municipio[]>([]); const [reviews, setReviews] = useState<Review[]>([]); const [places, setPlaces] = useState<Place[]>([]);
  const [selectedDestination, setSelectedDestination] = useState('');
  const [query, setQuery] = useState(''); const [municipalityQuery, setMunicipalityQuery] = useState(''); const [reviewQuery, setReviewQuery] = useState(''); const [placeQuery, setPlaceQuery] = useState(''); const [destinationQuery, setDestinationQuery] = useState('');
  const [loading, setLoading] = useState(true); const [editorLoading, setEditorLoading] = useState(false); const [saving, setSaving] = useState(false);
  const [feedback, setFeedback] = useState<{ tone: 'error' | 'success'; text: string } | null>(null);
  const [destinationForm, setDestinationForm] = useState<Partial<Destino> | null>(null); const [municipioForm, setMunicipioForm] = useState<Partial<Municipio> | null>(null); const [placeForm, setPlaceForm] = useState<Partial<Place> | null>(null);

  const load = async () => {
    if (!token || user?.role !== 'admin') return;
    setLoading(true); setFeedback(null);
    try { const [destinationData, municipalityData, reviewData] = await Promise.all([api<Destino[]>('/admin/destinos', {}, token), api<Municipio[]>('/admin/municipios', {}, token), api<Review[]>('/admin/reviews', {}, token)]); setDestinos(destinationData); setMunicipios(municipalityData); setReviews(reviewData); setSelectedDestination((current) => current || destinationData[0]?.id || ''); }
    catch (cause) { setFeedback({ tone: 'error', text: cause instanceof Error ? cause.message : 'No se pudo cargar la administración' }); }
    finally { setLoading(false); }
  };
  useEffect(() => { void load(); }, [token, user?.role]);
  useEffect(() => { if (token && selectedDestination) api<Place[]>(`/admin/destinos/${selectedDestination}/places`, {}, token).then(setPlaces).catch((cause) => setFeedback({ tone: 'error', text: cause instanceof Error ? cause.message : 'No se pudieron cargar los lugares' })); }, [token, selectedDestination]);

  const filteredDestinations = useMemo(() => destinos.filter((item) => `${item.nombre} ${plain(item.ubicacion)} ${plain(item.tipoTurismoPrincipal)}`.toLowerCase().includes(query.toLowerCase())), [destinos, query]);
  const filteredMunicipalities = useMemo(() => municipios.filter((item) => `${item.nombre} ${plain(item.tipoTurismo)} ${plain(item.conexiones)}`.toLowerCase().includes(municipalityQuery.toLowerCase())), [municipios, municipalityQuery]);
  const filteredReviews = useMemo(() => reviews.filter((item) => `${item.destino?.nombre} ${item.user?.nombre} ${item.comment}`.toLowerCase().includes(reviewQuery.toLowerCase())), [reviews, reviewQuery]);
  const filteredPlaces = useMemo(() => places.filter((item) => `${item.nombre} ${item.categoria} ${item.descripcion}`.toLowerCase().includes(placeQuery.toLowerCase())), [places, placeQuery]);
  const destinationChoices = useMemo(() => destinos.filter((item) => item.nombre.toLowerCase().includes(destinationQuery.toLowerCase())), [destinos, destinationQuery]);

  const openDestination = async (summary: Destino) => {
    setEditorLoading(true); setFeedback(null);
    try { setDestinationForm(await api<Destino>(`/destinos/${summary.id}`)); }
    catch (cause) { setFeedback({ tone: 'error', text: cause instanceof Error ? cause.message : 'No se pudo abrir el destino completo' }); }
    finally { setEditorLoading(false); }
  };
  const destinationChanged = (destination: Destino) => setDestinos((current) => [...current.filter((item) => item.id !== destination.id), destination].sort((a, b) => a.nombre.localeCompare(b.nombre, 'es')));
  const saveMunicipality = async (event: React.FormEvent) => {
    event.preventDefault(); if (!token || !municipioForm) return; setSaving(true); setFeedback(null);
    try { await api(`/admin/municipios${municipioForm.id ? `/${municipioForm.id}` : ''}`, { method: municipioForm.id ? 'PUT' : 'POST', body: JSON.stringify(municipioForm) }, token); setMunicipioForm(null); setFeedback({ tone: 'success', text: 'Municipio guardado' }); await load(); }
    catch (cause) { setFeedback({ tone: 'error', text: cause instanceof Error ? cause.message : 'No se pudo guardar el municipio' }); }
    finally { setSaving(false); }
  };
  const savePlace = async (event: React.FormEvent) => {
    event.preventDefault(); if (!token || !placeForm || !selectedDestination) return; setSaving(true); setFeedback(null);
    try { const path = placeForm.id ? `/admin/places/${placeForm.id}` : `/admin/destinos/${selectedDestination}/places`; await api(path, { method: placeForm.id ? 'PUT' : 'POST', body: JSON.stringify({ ...placeForm, latitud: Number(placeForm.latitud), longitud: Number(placeForm.longitud), sortOrder: Number(placeForm.sortOrder || 0), isActive: placeForm.isActive !== false }) }, token); setPlaceForm(null); setPlaces(await api<Place[]>(`/admin/destinos/${selectedDestination}/places`, {}, token)); setFeedback({ tone: 'success', text: 'Lugar guardado' }); }
    catch (cause) { setFeedback({ tone: 'error', text: cause instanceof Error ? cause.message : 'No se pudo guardar el lugar' }); }
    finally { setSaving(false); }
  };
  const remove = async (kind: 'destinos' | 'municipios' | 'places', id: string) => {
    if (!token || !confirm('¿Eliminar este elemento definitivamente? Esta acción no se puede deshacer.')) return;
    try { await api(`/admin/${kind}/${id}`, { method: 'DELETE' }, token); if (kind === 'places') setPlaces((items) => items.filter((item) => item.id !== id)); else await load(); setFeedback({ tone: 'success', text: 'Elemento eliminado' }); }
    catch (cause) { setFeedback({ tone: 'error', text: cause instanceof Error ? cause.message : 'No se pudo eliminar' }); }
  };
  const moderate = async (id: string, status: 'published' | 'hidden') => { if (!token) return; try { await api(`/admin/reviews/${id}`, { method: 'PATCH', body: JSON.stringify({ status }) }, token); setReviews((current) => current.map((review) => review.id === id ? { ...review, status } : review)); setFeedback({ tone: 'success', text: status === 'published' ? 'Reseña publicada' : 'Reseña oculta' }); } catch (cause) { setFeedback({ tone: 'error', text: cause instanceof Error ? cause.message : 'No se pudo moderar la reseña' }); } };

  if (authLoading) return <Shell footer={false}><Loader /></Shell>;
  if (!user || user.role !== 'admin') return <Shell footer={false}><section className="status-page"><Empty headingLevel="h1" icon={<ShieldCheck />} title="Acceso restringido">Esta zona solo está disponible para administradores.</Empty></section></Shell>;

  return <Shell footer={false}><PageHeading kicker="Back office" title="Administración"><p>Gestiona destinos, municipios, lugares y reseñas sin tocar código.</p></PageHeading>
    <div className="admin-layout"><nav className="admin-nav" aria-label="Administración">{([['destinos','Destinos',MapPin],['municipios','Municipios',Building2],['reviews','Reseñas',MessageSquare],['places','Lugares',MapPin]] as const).map(([id, label, Icon]) => <button key={id} className={tab === id ? 'is-active' : ''} onClick={() => setTab(id)} aria-current={tab === id ? 'page' : undefined}><Icon /> {label}<span>{id === 'destinos' ? destinos.length : id === 'municipios' ? municipios.length : id === 'reviews' ? reviews.length : places.length}</span></button>)}</nav>
      <section className="admin-workspace" aria-live="polite">{feedback && <Notice tone={feedback.tone}>{feedback.text}</Notice>}{loading ? <Loader /> : <>
        {tab === 'destinos' && <><AdminToolbar query={query} setQuery={setQuery} placeholder="Buscar por nombre, zona o tipo" resultCount={filteredDestinations.length}><Button onClick={() => setDestinationForm({ ...emptyDestination })}><Plus /> Nuevo destino</Button></AdminToolbar>{editorLoading && <Loader label="Abriendo todos los datos" />}<div className="admin-list">{filteredDestinations.map((item) => <article key={item.id}><div><span>{plain(item.ubicacion)}</span><h2>{item.nombre}</h2><div className="admin-list__meta"><TourismMark value={item.tipoTurismoPrincipal} compact /><small>{plain(item.presupuesto)} · {item.municipios?.length || 0} municipios{item.latitud == null ? ' · Sin punto en mapa' : ''}</small></div></div><div><button onClick={() => void openDestination(item)} aria-label={`Editar ${item.nombre}`}><Edit3 /></button><button onClick={() => void remove('destinos', item.id)} aria-label={`Eliminar ${item.nombre}`}><Trash2 /></button></div></article>)}</div></>}
        {tab === 'municipios' && <><AdminToolbar query={municipalityQuery} setQuery={setMunicipalityQuery} placeholder="Buscar municipio, tipo o conexión" resultCount={filteredMunicipalities.length}><Button onClick={() => setMunicipioForm({ nombre: '', precios: '', conexiones: '', tipoTurismo: '' })}><Plus /> Nuevo municipio</Button></AdminToolbar>{filteredMunicipalities.length > 100 && <p className="admin-result-hint">Mostrando los primeros 100. Escribe un nombre, tipo o conexión para acotar la lista.</p>}<div className="admin-list">{filteredMunicipalities.slice(0, 100).map((item) => <article key={item.id}><div><span>{item.destinosCount || 0} destinos asociados</span><h2>{item.nombre}</h2><p>{plain(item.tipoTurismo) || 'Sin tipo'} · {plain(item.precios) || 'Precios sin indicar'}</p></div><div><button onClick={() => setMunicipioForm(item)} aria-label={`Editar ${item.nombre}`}><Edit3 /></button><button onClick={() => void remove('municipios', item.id)} aria-label={`Eliminar ${item.nombre}`}><Trash2 /></button></div></article>)}</div></>}
        {tab === 'reviews' && <><AdminToolbar query={reviewQuery} setQuery={setReviewQuery} placeholder="Buscar destino, persona o comentario" resultCount={filteredReviews.length} /><div className="admin-list">{filteredReviews.map((review) => <article key={review.id}><div><span>{review.destino?.nombre || 'Destino'} · {review.status === 'published' ? 'Publicada' : 'Oculta'}</span><h2>{review.rating}/5 · {review.user?.nombre || 'Usuario'}</h2><p>{review.comment || 'Sin comentario'}</p></div><div><Button variant={review.status === 'published' ? 'secondary' : 'primary'} onClick={() => void moderate(review.id, review.status === 'published' ? 'hidden' : 'published')}>{review.status === 'published' ? 'Ocultar' : 'Publicar'}</Button></div></article>)}</div></>}
        {tab === 'places' && <><div className="admin-place-context"><div><label htmlFor="destination-filter">Buscar destino</label><div className="admin-search"><Search /><input id="destination-filter" value={destinationQuery} onChange={(event) => setDestinationQuery(event.target.value)} placeholder="Filtrar destinos" /></div></div><Field label="Destino activo" htmlFor="places-destination"><select id="places-destination" value={selectedDestination} onChange={(event) => setSelectedDestination(event.target.value)}>{destinationChoices.map((item) => <option key={item.id} value={item.id}>{item.nombre}</option>)}</select></Field></div><AdminToolbar query={placeQuery} setQuery={setPlaceQuery} placeholder="Buscar lugar o categoría" resultCount={filteredPlaces.length}><Button onClick={() => setPlaceForm({ nombre: '', categoria: '', descripcion: '', latitud: 40.2, longitud: -3.5, website: '', sortOrder: 0, isActive: true })}><Plus /> Nuevo lugar</Button></AdminToolbar><div className="admin-list">{filteredPlaces.length ? filteredPlaces.map((place) => <article key={place.id}><div><span>{place.categoria} · {place.isActive === false ? 'Oculto' : 'Visible'} · orden {place.sortOrder || 0}</span><h2>{place.nombre}</h2><p>{place.descripcion || 'Sin descripción'}</p>{place.website && <a href={place.website} target="_blank" rel="noreferrer">Abrir web <ExternalLink /></a>}</div><div><button onClick={() => setPlaceForm(place)} aria-label={`Editar ${place.nombre}`}><Edit3 /></button><button onClick={() => void remove('places', place.id)} aria-label={`Eliminar ${place.nombre}`}><Trash2 /></button></div></article>) : <Empty title="Este destino no tiene lugares">Añade miradores, monumentos, playas u otros puntos útiles.</Empty>}</div></>}
      </>}</section>
    </div>
    {destinationForm && token && <DestinationEditor initial={destinationForm} municipalities={municipios} token={token} onChange={destinationChanged} onClose={() => setDestinationForm(null)} />}
    {municipioForm && <AdminModal title={municipioForm.id ? 'Editar municipio' : 'Nuevo municipio'} subtitle="Información práctica que se reutiliza en todos los destinos asociados." onClose={() => setMunicipioForm(null)}><form onSubmit={saveMunicipality}><Field label="Nombre" htmlFor="mun-name"><input id="mun-name" value={municipioForm.nombre || ''} onChange={(event) => setMunicipioForm({ ...municipioForm, nombre: event.target.value })} required /></Field><Field label="Nivel de precios" htmlFor="mun-price"><input id="mun-price" value={plain(municipioForm.precios)} onChange={(event) => setMunicipioForm({ ...municipioForm, precios: event.target.value })} placeholder="30–50 € por noche" /></Field><Field label="Conexiones y transporte" htmlFor="mun-conn"><textarea id="mun-conn" value={plain(municipioForm.conexiones)} onChange={(event) => setMunicipioForm({ ...municipioForm, conexiones: event.target.value })} placeholder="Autobús, tren, carretera y tiempos aproximados" /></Field><Field label="Tipo de turismo" htmlFor="mun-type"><input id="mun-type" value={plain(municipioForm.tipoTurismo)} onChange={(event) => setMunicipioForm({ ...municipioForm, tipoTurismo: event.target.value })} /></Field><Button type="submit" loading={saving}>Guardar municipio</Button></form></AdminModal>}
    {placeForm && <AdminModal wide title={placeForm.id ? 'Editar lugar' : 'Nuevo lugar'} subtitle="Un punto concreto que ayuda a recorrer el destino." onClose={() => setPlaceForm(null)}><form onSubmit={savePlace} className="place-editor"><div className="form-grid"><Field label="Nombre" htmlFor="place-name"><input id="place-name" value={placeForm.nombre || ''} onChange={(event) => setPlaceForm({ ...placeForm, nombre: event.target.value })} required /></Field><Field label="Categoría" htmlFor="place-category"><select id="place-category" value={placeForm.categoria || ''} onChange={(event) => setPlaceForm({ ...placeForm, categoria: event.target.value })} required><option value="">Elige una categoría</option>{['Mirador','Patrimonio','Naturaleza','Playa','Museo','Gastronomía','Actividad','Alojamiento','Otro'].map((value) => <option key={value}>{value}</option>)}</select></Field></div><Field label="Descripción" htmlFor="place-description"><textarea id="place-description" value={placeForm.descripcion || ''} onChange={(event) => setPlaceForm({ ...placeForm, descripcion: event.target.value })} /></Field><div className="form-grid"><Field label="Sitio web" htmlFor="place-web"><input id="place-web" type="url" value={placeForm.website || ''} onChange={(event) => setPlaceForm({ ...placeForm, website: event.target.value })} placeholder="https://" /></Field><Field label="Orden" htmlFor="place-order"><input id="place-order" type="number" min="0" max="9999" value={placeForm.sortOrder || 0} onChange={(event) => setPlaceForm({ ...placeForm, sortOrder: Number(event.target.value) })} /></Field></div><label className="setting-row"><span><b>Visible en la ficha pública</b><small>Desactívalo para conservarlo sin mostrarlo.</small></span><input type="checkbox" checked={placeForm.isActive !== false} onChange={(event) => setPlaceForm({ ...placeForm, isActive: event.target.checked })} /></label><CoordinatePicker compact latitude={placeForm.latitud} longitude={placeForm.longitud} onChange={(latitud, longitud) => setPlaceForm({ ...placeForm, latitud, longitud })} /><div className="form-grid"><Field label="Latitud" htmlFor="place-lat"><input id="place-lat" type="number" step="any" value={placeForm.latitud ?? ''} onChange={(event) => setPlaceForm({ ...placeForm, latitud: Number(event.target.value) })} required /></Field><Field label="Longitud" htmlFor="place-lng"><input id="place-lng" type="number" step="any" value={placeForm.longitud ?? ''} onChange={(event) => setPlaceForm({ ...placeForm, longitud: Number(event.target.value) })} required /></Field></div><Button type="submit" loading={saving}>Guardar lugar</Button></form></AdminModal>}
  </Shell>;
}

function AdminToolbar({ query, setQuery, placeholder, resultCount, children }: { query: string; setQuery: (value: string) => void; placeholder: string; resultCount: number; children?: React.ReactNode }) {
  return <header className="admin-workspace__head"><div><label className="admin-search"><Search /><span className="sr-only">{placeholder}</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={placeholder} /></label><small>{resultCount} resultados</small></div>{children}</header>;
}
